---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ${CI_HOSTNAME}-${CI_PROJECT_NAME_MOLECULE}-${CI_JOB_ID}
    image: schmitzis/molecule:${MOLECULE_DISTRO}
    command: ${MOLECULE_DOCKER_COMMAND:-"/lib/systemd/systemd"}
    pre_build_image: true
    dns_servers:
      - 1.1.1.1
      - 8.8.8.8
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  config_options:
    defaults:
      bin_ansible_callbacks: yes
      callbacks_enabled: timer, profile_tasks, yaml
      display_failed_stderr: true
      fact_caching: jsonfile
      fact_caching_connection: '/tmp'
      host_key_checking: false
      remote_tmp: '/tmp/.ansible-${USER}/tmp'
      stdout_callback: yaml
    diff:
      always: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  log: True
verifier:
  name: ansible
