---
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    - cron: "0 2 * * 0"

jobs:

  test:
    name: "${{ matrix.image }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian-10
          - debian-11
          - ubuntu-20.04
          - ubuntu-22.04

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Install yq via wget
        run: sudo wget -qO /usr/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && sudo chmod +x /usr/bin/yq
        shell: bash

      - name: Set CI_HOSTNAME
        run: echo "CI_HOSTNAME=$(echo $MOLECULE_DISTRO | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        shell: bash
        env:
          MOLECULE_DISTRO: "${{ inputs.distro }}"

      - name: Set CI_PROJECT_NAME_MOLECULE
        run: echo "CI_PROJECT_NAME_MOLECULE=$(echo $GITHUB_REPOSITORY_OWNER | tr '_' '-')" >> $GITHUB_ENV
        shell: bash

      - name: Install test dependencies
        run: pip install ansible ansible-lint molecule[docker] docker netaddr jmespath dnspython
        shell: bash

      - name: Print molecule version infos
        run: molecule --version
        shell: bash

      - name: Run Molecule tests
        run: molecule test
        shell: bash
        env:
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_VERBOSITY: '2'
          CI_JOB_ID: "${{ github.run_id }}"
          MOLECULE_DEBUG: '1'
          MOLECULE_DISTRO: "${{ matrix.image }}"
          PY_COLORS: '1'
